library(ggplot2)
setwd("C:/Users/lebmd/OneDrive/Desktop/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports")
COVID1= read.csv(file.choose(),header = T)
COVID1= data.frame(COVID1)
attach(COVID1)
names(COVID1)
plot(COVID1$Deaths,COVID1$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 01-23-2020")
hist(COVID1$Deaths,main = "tỉ lệ sống chết giữa các quốc gia vào 01-23-2020", breaks = 40)


COVID1.5= read.csv(file.choose(),header = T)
COVID1.5= data.frame(COVID1.5)
attach(COVID1.5)
names(COVID1.5)
plot(COVID1.5$Deaths,COVID1.5$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 12-31-2020")
hist(COVID1.5$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 12-31-2020", breaks = 40)
hist(COVID1.5$Recovered,col=c("yellow"),main = "tỉ lệ phục hồi giữa các quốc gia vào 12-31-2020", breaks = 50)
hist(COVID1.5$Incident_Rate,col=c("yellow"),main = "tỉ lệ tai nạn covid giữa các quốc gia vào 12-31-2020", breaks = 50)

COVID2= read.csv(file.choose(),header = T)
COVID2= data.frame(COVID2)
attach(COVID2)
names(COVID2)
plot(COVID2$Deaths,COVID2$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 01-01-2021")
hist(COVID2$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 01-01-2021", breaks = 40)
hist(COVID2$Recovered,col=c("yellow"),main = "tỉ lệ phục hồi giữa các quốc gia vào 01-01-2021", breaks = 50)
hist(COVID2$Total_Test_Results,col=c("yellow"),main = "tỉ lệ kết quả xét nghiệm giữa các quốc gia vào 01-01-2021", breaks = 50)


COVID2.5= read.csv(file.choose(),header = T)
COVID2.5= data.frame(COVID2.5)
attach(COVID2.5)
names(COVID2.5)
plot(COVID2.5$Deaths,COVID2.5$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 07-08-2021")
hist(COVID2.5$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 07-08-2021", breaks = 40)
hist(COVID2.5$Testing_Rate,col=c("yellow"),main = "tỉ lệ kiểm tra xét nghiệm giữa các quốc gia vào 07-08-2021", breaks = 50)
hist(COVID2.5$Total_Test_Results,col=c("yellow"),main = "tỉ lệ kết quả kiểm tra xét nghiệm giữa các quốc gia vào 07-08-2021", breaks = 50)

COVID1_US= read.csv(file.choose(),header = T)
COVID1_US= data.frame(COVID1_US)
attach(COVID1_US)
names(COVID1_US)
plot(COVID1_US$Deaths,COVID1_US$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 04-13-2020 ở US")
hist(COVID1_US$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 04-13-2020 ở US", breaks = 40)
hist(COVID1_US$Recovered,col=c("yellow"),main = "tỉ lệ phục hồi giữa các quốc gia vào 04-13-2020 ở US", breaks = 50)
hist(COVID1_US$Testing_Rate,col=c("yellow"),main = "tỉ lệ kiểm tra xét nghiệm giữa các quốc gia vào 04-13-2020 ở US", breaks = 50)

COVID1.5_US= read.csv(file.choose(),header = T)
COVID1.5_US= data.frame(COVID1.5_US)
attach(COVID1.5_US)
names(COVID1.5_US)
plot(COVID1.5_US$Deaths,COVID1.5_US$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 12-31-2020 ở US")
hist(COVID1.5_US$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 12-31-2020 ở US", breaks = 40)
hist(COVID1.5_US$Recovered,col=c("yellow"),main = "tỉ lệ phục hồi giữa các quốc gia vào 12-31-2020 ở US", breaks = 50)
hist(COVID1.5_US$Testing_Rate,col=c("yellow"),main = "tỉ lệ kiểm tra xét nghiệm giữa các quốc gia vào 12-31-2020 ở US", breaks = 50)

COVID2_US= read.csv(file.choose(),header = T)
COVID2_US= data.frame(COVID2_US)
attach(COVID2_US)
names(COVID2_US)
plot(COVID2_US$Deaths,COVID2_US$Confirmed,col=c("darkblue","red"), xlab = "Deaths", ylab = "Confirmed", main = "tỉ lệ sống chết giữa các quốc gia vào 07-08-2021 ở US")
hist(COVID2_US$Deaths,col=c("darkblue","red"),main = "tỉ lệ sống chết giữa các quốc gia vào 07-08-2021 ở US", breaks = 40)
hist(COVID2_US$Total_Test_Results,col=c("yellow"),main = "tỉ lệ kết quả kiểm tra giữa các quốc gia vào 07-08-2021 ở US", breaks = 50)
hist(COVID2_US$Testing_Rate,col=c("yellow"),main = "tỉ lệ kiểm tra xét nghiệm giữa các quốc gia vào 07-08-2021 ở US", breaks = 50)
